const MenuItems = [
	{
		id: 1,
		image: "/images/chilli-maggi.jpg",
		name: "maggi",
		category: "breakfast",
		price: 50.12,
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
		quantity: 1,
	},

	{
		id: 2,
		image: "/images/breakfast2.png",
		name: "Breakfast Sandwich",
		category: "evening",
		price: 100.45,
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
		quantity: 1,
	},
	{
		id: 3,
		image: "/images/breakfast1.png",
		name: "Eggs Benedict",
		category: "breakfast",
		price: 150.03,
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
		quantity: 1,
	},
	{
		id: 4,
		image: "/images/Chole-Bowls.jpg",
		name: "chola",
		category: "lunch",
		price: 50.61,
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
		quantity: 1,
	},
	{
		id: 5,
		image: "/images/pizzas.png",
		name: "pizza",
		category: "evening",
		price: 200.0,
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
		quantity: 1,
	},
	{
		id: 6,
		image: "/images/non-veg.png",
		name: "Non-Veg Thali",
		category: "dinner",
		price: 180.06,
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
		quantity: 1,
	},
	{
		id: 7,
		image: "/images/sweet-3.jpg",
		name: "Sweets",
		category: "dinner",
		price: 60.36,
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
		quantity: 1,
	},
	{
		id: 8,
		image: "images/rajma.png",
		name: "Rajma Rice",
		category: "lunch",
		price: 60.21,
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
		quantity: 1,
	},
	{
		id: 9,
		image: "/images/lunch4.png",
		name: "Indian Puri Bhaji",
		category: "evening",
		price: 80.05,
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
		quantity: 1,
	},
	{
		id: 10,
		image: "images/Samosachutney.jpg",
		name: "samaso",
		category: "evening",
		price: 25.0,
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
		quantity: 1,
	},
	{
		id: 11,
		image: "images/pasta.png",
		name: "pasta",
		category: "evening",
		price: 60.71,
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
		quantity: 1,
	},
	{
		id: 12,
		image: "/images/dinner2.png",
		name: "Lemony Salmaon Piccata",
		category: "evening",
		price: 120.1,
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
		quantity: 1,
	},
];

export default MenuItems;
